"""erpc.py — Python subprocess manager for eRPC."""

from erpc.auth import AuthConfig, JWTAuth, NetworkAuth, SecretAuth, SIWEAuth
from erpc.config import CacheConfig, ERPCConfig
from erpc.database import (
    CachePolicy,
    CompressionConfig,
    DatabaseConfig,
    DynamoDBConnector,
    MemoryConnector,
    PostgresConnector,
    RedisConnector,
    TLSConfig,
)
from erpc.docker import DockerERPCProcess
from erpc.dynamic import (
    ConfigDiff,
    add_upstream,
    atomic_write_config,
    remove_upstream,
    update_config,
)
from erpc.failsafe import (
    CircuitBreakerPolicy,
    FailsafeConfig,
    FailsafePresets,
    HedgePolicy,
    MethodFailsafeConfig,
    RetryPolicy,
    TimeoutPolicy,
)
from erpc.exceptions import (
    ERPCConfigError,
    ERPCError,
    ERPCHealthCheckError,
    ERPCNotFound,
    ERPCNotRunning,
    ERPCStartupError,
)
from erpc.logging import ERPCLogStream
from erpc.rate_limiters import (
    AutoTuneConfig,
    MemoryStore,
    RateLimiterConfig,
    RateLimitBudget,
    RateLimitRule,
    RedisStore,
)
from erpc.mixins import LoggingMixin
from erpc.monitoring import HealthEvent, HealthMonitor, HealthStatus
from erpc.process import ERPCProcess
from erpc.providers import (
    AlchemyProvider,
    AnkrProvider,
    BlastAPIProvider,
    BlockPiProvider,
    ChainstackProvider,
    ConduitProvider,
    DrpcProvider,
    DwellirProvider,
    EnvioProvider,
    EtherspotProvider,
    InfuraProvider,
    OnFinalityProvider,
    PimlicoProvider,
    Provider,
    QuickNodeProvider,
    RepositoryProvider,
    RouteMeshProvider,
    SuperchainProvider,
    TenderlyProvider,
    ThirdwebProvider,
)
from erpc.server import CORSConfig, MetricsConfig, ServerConfig

__all__ = [
    "AlchemyProvider",
    "AutoTuneConfig",
    "AnkrProvider",
    "AuthConfig",
    "BlastAPIProvider",
    "BlockPiProvider",
    "CORSConfig",
    "CacheConfig",
    "CachePolicy",
    "CircuitBreakerPolicy",
    "ConfigDiff",
    "ChainstackProvider",
    "CompressionConfig",
    "ConduitProvider",
    "DatabaseConfig",
    "DockerERPCProcess",
    "DrpcProvider",
    "DwellirProvider",
    "DynamoDBConnector",
    "ERPCConfig",
    "FailsafeConfig",
    "FailsafePresets",
    "ERPCConfigError",
    "ERPCError",
    "ERPCHealthCheckError",
    "ERPCLogStream",
    "ERPCNotFound",
    "ERPCNotRunning",
    "ERPCProcess",
    "ERPCStartupError",
    "EnvioProvider",
    "EtherspotProvider",
    "HedgePolicy",
    "HealthEvent",
    "HealthMonitor",
    "HealthStatus",
    "InfuraProvider",
    "JWTAuth",
    "LoggingMixin",
    "MemoryConnector",
    "MemoryStore",
    "MethodFailsafeConfig",
    "MetricsConfig",
    "NetworkAuth",
    "OnFinalityProvider",
    "PimlicoProvider",
    "PostgresConnector",
    "Provider",
    "RateLimiterConfig",
    "RateLimitBudget",
    "RateLimitRule",
    "RedisStore",
    "RetryPolicy",
    "QuickNodeProvider",
    "RedisConnector",
    "RepositoryProvider",
    "RouteMeshProvider",
    "SIWEAuth",
    "SecretAuth",
    "ServerConfig",
    "SuperchainProvider",
    "TLSConfig",
    "TenderlyProvider",
    "TimeoutPolicy",
    "ThirdwebProvider",
    "add_upstream",
    "atomic_write_config",
    "remove_upstream",
    "update_config",
]

__version__ = "0.1.0"
